name: Backend Changes Workflow

on:
  pull_request:
    paths:
      - 'backend/**'
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  backend-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check backend changes on push
        run: |
          echo "Changes detected in the backend directory on push."

      - name: Check backend changes on PR merge
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Changes detected in the backend directory after merging PR."
