name: Backend Changes Workflow

on:
  pull_request:
    paths:
      - 'backend/**'
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  release:
    types: [published]

jobs:
  backend-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check backend changes on push
        run: |
          echo "Changes detected in the backend directory on push."

      - name: Check backend changes on PR merge
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Changes detected in the backend directory after merging PR."

      - name: Check backend changes on release
        if: github.event_name == 'release'
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          previous_tag=$(git describe --tags `git rev-list --tags --skip=1 --max-count=1`)
          if git diff --name-only $previous_tag $latest_tag | grep -q '^backend/'; then
            echo "Changes detected in the backend directory between releases."
          else
            echo "No changes detected in the backend directory between releases."
          fi
