name: Frontend Changes Workflow

on:
  pull_request:
    paths:
      - 'frontend/**'
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  release:
    types: [published]

jobs:
  frontend-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check frontend changes on push
        run: |
          echo "Changes detected in the frontend directory on push."

      - name: Check frontend changes on PR merge
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Changes detected in the frontend directory after merging PR."

      - name: Check frontend changes on release
        if: github.event_name == 'release'
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          previous_tag=$(git describe --tags `git rev-list --tags --skip=1 --max-count=1`)
          if git diff --name-only $previous_tag $latest_tag | grep -q '^frontend/'; then
            echo "Changes detected in the frontend directory between releases."
          else
            echo "No changes detected in the frontend directory between releases."
          fi
