name: Frontend Changes Workflow


on:
  pull_request:
    paths:
      - 'frontend/**'
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  frontend-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check frontend changes on push
        run: |
          echo "Changes detected in the frontend directory on push."

      - name: Check frontend changes on PR merge
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Changes detected in the frontend directory after merging PR."
