name: CI/CD Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'

jobs:
  backend:
    if: "contains(github.event.commits[0].modified, 'backend/') || contains(github.event.commits[0].added, 'backend/') || contains(github.event.commits[0].removed, 'backend/')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo backend changes
        run: |
          echo "Changes detected in the backend directory."

  frontend:
    if: "contains(github.event.commits[0].modified, 'frontend/') || contains(github.event.commits[0].added, 'frontend/') || contains(github.event.commits[0].removed, 'frontend/')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo frontend changes
        run: |
          echo "Changes detected in the frontend directory."
