name: Test Main Merge and Release Branch

on:
  push:
    branches:
      - main
      - release

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Build application
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: build/

  deploy-main:
    name: Deploy to Main Environment
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build-output
      - name: Deploy to main environment
        run: |
          # Add your deployment steps for the main environment here
          echo "Deploying to main environment..."

  deploy-release:
    name: Deploy to Release Environment
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/release'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build-output
      - name: Deploy to release environment
        run: |
          # Add your deployment steps for the release environment here
          echo "Deploying to release environment..."