name: Test Main Merge and Release Branch

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build application
        run: npm run build

  deploy-staging:
    name: Deploy to Staging Environment
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to staging environment
        run: |
          # Add your deployment steps for the staging environment here
          echo "Deploying to staging environment..."

  deploy-production:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to production environment
        run: |
          # Add your deployment steps for the production environment here
          echo "Deploying to production environment..."